---
- name: instal epel-release repositories
  dnf:
    name: epel-release
  become: true
  
- name: install Mosquitto
  dnf:
    name: mosquitto
  become: true
  
- name: enable and start Mosquitto service
  service:
    name: mosquitto
    enabled: true
    state: started
  become: true
  
- name: add mqtt port to firewall
  command: firewall-cmd --permanent --add-service=mqtt
  become: true

- name: restart firewall service
  command: firewall-cmd --reload
  become: true
 
- name: copying pwfile into Mosquitto directory
  copy:
    src: pwfile
    dest: /etc/mosquitto/pwfile
  become: true
  notify: restart mosquitto

- name: copying mosquitto.conf into Mosquitto directory
  copy:
    src: mosquitto.conf
    dest: /etc/mosquitto/mosquitto.conf
  become: true
  notify: restart mosquitto
