---
- name: instal epel-release repositories
  dnf:
    name: epel-release
  become: true
  
- name: install Mosquitto
  dnf:
    name: mosquitto
  become: true
  
- name: enable and start Mosquitto service
  service:
    name: mosquitto
    enabled: true
    state: started
  become: true
